from pySDC.core.hooks import Hooks


class LogGlobalErrorPostStepDifferentialVariable(Hooks):
    """
    Hook class to log the error to the output generated by the sweeper after
    each time step.
    """

    def post_step(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.step.Step
            Current step.
        level_number : pySDC.core.level.Level
            Current level number.
        """

        super().post_step(step, level_number)

        # some abbreviations
        L = step.levels[level_number]
        P = L.prob

        # TODO: is it really necessary to recompute the end point? Hasn't this been done already?
        L.sweep.compute_end_point()

        # compute and save errors
        # Note that the component from which the error is measured is specified here
        upde = P.u_exact(step.time + step.dt)
        e_global_differential = abs(upde.diff - L.uend.diff)

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_differential_post_step",
            value=e_global_differential,
        )


class LogGlobalErrorPostStepAlgebraicVariable(Hooks):
    """
    Logs the global error in the algebraic variable after each step.
    """

    def post_step(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.step.Step
            Current step.
        level_number : pySDC.core.level.Level
            Current level number.
        """

        super().post_step(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        upde = P.u_exact(step.time + step.dt)
        e_global_algebraic = abs(upde[:].alg - L.uend[:].alg)
        # print(L.time + L.dt, e_global_algebraic)
        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_algebraic_post_step",
            value=e_global_algebraic,
        )


class LogGlobalErrorPostIterDiff(Hooks):
    """
    Logs the global error in the differential variable and its derivative after each iteration.
    """

    def post_iteration(self, step, level_number):
        super().post_iteration(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        upde = P.u_exact(step.time + step.dt)
        e_global = abs(upde.diff - L.uend.diff)

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_differential_post_iteration",
            value=e_global,
        )


class LogGlobalErrorPostIterAlg(Hooks):
    """
    Logs the global error in the algebraic variable and its derivative after each iteration.
    """

    def post_iteration(self, step, level_number):
        super().post_iteration(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        upde = P.u_exact(step.time + step.dt)
        e_global_algebraic = abs(upde[:].alg - L.uend[:].alg)
        # print(L.time + L.dt, step.status.iter, e_global_algebraic)
        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_algebraic_post_iteration",
            value=e_global_algebraic,
        )


class LogGlobalErrorPostSweepDiff(Hooks):
    """
    Logs the global error in the differential variable and its derivative after each sweep.
    """

    def post_sweep(self, step, level_number):
        super().post_sweep(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        upde = P.u_exact(step.time + step.dt)
        e_global = abs(upde.diff - L.uend.diff)

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_differential_post_sweep",
            value=e_global,
        )


class LogGlobalErrorPostSweepAlg(Hooks):
    """
    Logs the global error in the algebraic variable and its derivative after each sweep.
    """

    def post_sweep(self, step, level_number):
        super().post_sweep(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        upde = P.u_exact(step.time + step.dt)
        e_global_algebraic = abs(upde[:].alg - L.uend[:].alg)
        # print(L.time + L.dt, step.status.iter, e_global_algebraic)
        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_algebraic_post_sweep",
            value=e_global_algebraic,
        )
