import numpy as np
from pySDC.core.hooks import Hooks


class LogGlobalErrorPostStep(Hooks):
    r"""
    Hook class to log the error to the output generated by the sweeper after
    each time step.

    Here, the error is logged for all components **except** for the last one,
    which can be logged by using ``LogGlobalErrorPostStepAlgebraicVariable``.
    """

    def post_step(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_step(step, level_number)

        # some abbreviations
        L = step.levels[level_number]
        P = L.prob

        # TODO: is it really necessary to recompute the end point? Hasn't this been done already?
        L.sweep.compute_end_point()

        # compute and save errors
        # Note that the component from which the error is measured is specified here
        upde = P.u_exact(step.time + step.dt)
        e_global = abs(upde[:-1] - L.uend[:-1])

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_differential_post_step",
            value=e_global,
        )


class LogGlobalErrorPostStepPerturbation(Hooks):
    """
    Logs the global error in the variable with perturbation parameter :math:`\varepsilon`
    that represents the algebraic variable.

    Here, the error is logged **only** for the last component.
    """

    def post_step(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_step(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        upde = P.u_exact(step.time + step.dt)
        e_global_algebraic = abs(upde[-1] - L.uend[-1])

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_algebraic_post_step",
            value=e_global_algebraic,
        )


class LogGlobalErrorPostStepPerturbationScaled(Hooks):
    """
    Logs the global error in the variable with perturbation parameter :math:`\varepsilon`
    that represents the algebraic variable. Algebraic variable is scaled with
    :math:`1 / \varepsilon`.

    Here, the error is logged **only** for the last component.
    """

    def post_step(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_step(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        upde = P.u_exact(step.time + step.dt)

        uend = L.uend.copy()

        uend[-1] *= 1 / P.eps
        e_global_algebraic = abs(upde[-1] - uend[-1])

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_algebraic_post_step_scaled",
            value=e_global_algebraic,
        )


class LogGlobalErrorPostIter(Hooks):
    r"""
    Hook class to log the error to the output generated by the sweeper after
    each time step.

    Here, the error is logged for all components **except** for the last one,
    which can be logged by using ``LogGlobalErrorPostStepAlgebraicVariable``.
    """

    def post_iteration(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_iteration(step, level_number)

        # some abbreviations
        L = step.levels[level_number]
        P = L.prob

        # TODO: is it really necessary to recompute the end point? Hasn't this been done already?
        L.sweep.compute_end_point()

        # compute and save errors
        # Note that the component from which the error is measured is specified here
        upde = P.u_exact(step.time + step.dt)
        e_global = abs(upde[:-1] - L.uend[:-1])

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_differential_post_iteration",
            value=e_global,
        )


class LogGlobalErrorPostIterPerturbation(Hooks):
    """
    Logs the global error in the variable with perturbation parameter :math:`\varepsilon`
    that represents the algebraic variable.

    Here, the error is logged **only** for the last component.
    """

    def post_iteration(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_iteration(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        upde = P.u_exact(step.time + step.dt)
        e_global_algebraic = abs(upde[-1] - L.uend[-1])

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_algebraic_post_iteration",
            value=e_global_algebraic,
        )


class LogGlobalErrorPostSweep(Hooks):
    r"""
    Hook class to log the error to the output generated by the sweeper after
    each sweep.

    Here, the error is logged for all components **except** for the last one,
    which can be logged by using ``LogGlobalErrorPostStepAlgebraicVariable``.
    """

    def post_sweep(self, step, level_number):
        r"""
        Default routine called after each sweep.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_sweep(step, level_number)

        # some abbreviations
        L = step.levels[level_number]
        P = L.prob

        # TODO: is it really necessary to recompute the end point? Hasn't this been done already?
        L.sweep.compute_end_point()

        # compute and save errors
        # Note that the component from which the error is measured is specified here
        upde = P.u_exact(step.time + step.dt)
        e_global = abs(upde[:-1] - L.uend[:-1])

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_differential_post_sweep",
            value=e_global,
        )


class LogGlobalErrorPostSweepPerturbation(Hooks):
    """
    Logs the global error in the variable with perturbation parameter :math:`\varepsilon`
    that represents the algebraic variable.

    Here, the error is logged **only** for the last component.
    """

    def post_sweep(self, step, level_number):
        r"""
        Default routine called after each sweep.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_sweep(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        upde = P.u_exact(step.time + step.dt)
        e_global_algebraic = abs(upde[-1] - L.uend[-1])

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_algebraic_post_sweep",
            value=e_global_algebraic,
        )


class LogGlobalErrorPostIterPerturbationScaled(Hooks):
    """
    Logs the global error in the variable with perturbation parameter :math:`\varepsilon`
    that represents the algebraic variable.

    Here, the error is logged **only** for the last component.
    """

    def post_iteration(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_iteration(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        upde = P.u_exact(step.time + step.dt)

        uend = L.uend.copy()

        uend[-1] *= 1 / P.eps
        e_global_algebraic = abs(upde[-1] - uend[-1])

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="e_global_algebraic_post_iteration_scaled",
            value=e_global_algebraic,
        )


class LogResidualComponentsPostIter(Hooks):
    """
    Logs the residual of all components of the system after each iteration.

    Parameters
    ----------
    Hooks : _type_
        _description_
    """

    def post_iteration(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_iteration(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        L = step.levels[level_number]

        L.sweep.compute_end_point()

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="residual_comp_post_iteration",
            value=L.sweep.residual_comp,
        )


class LogRHSPostIter(Hooks):
    def post_iteration(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_iteration(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        rhs = P.rhs
        rhs = np.array(rhs).flatten

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="rhs_post_iteration",
            value=rhs,
        )

        P.clear_rhs()


class LogRHSPostStep(Hooks):
    def post_step(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_step(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        M = L.sweep.coll.num_nodes

        # rhsM = P.rhs[-1:]
        rhsM = P.rhs[-M:]
        rhsM = [item for sublist in rhsM for item in sublist]
        rhsM = np.array(rhsM)

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="rhs_post_step",
            value=rhsM,
        )

        P.clear_rhs()


class LogJacPostIter(Hooks):
    def post_iteration(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_iteration(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="jac_post_iteration",
            value=P.jac,
        )


class LogJacPostStep(Hooks):
    def post_step(self, step, level_number):
        r"""
        Default routine called after each step.

        Parameters
        ----------
        step : pySDC.core.Step
            Current step.
        level_number : pySDC.core.level
            Current level number.
        """

        super().post_step(step, level_number)

        L = step.levels[level_number]
        P = L.prob

        L.sweep.compute_end_point()

        jacM = P.jac[-1:]  # P.jac[-M:]
        jacM = [item for sublist in jacM for item in sublist]
        jacM = np.array(jacM)

        self.add_to_stats(
            process=step.status.slot,
            time=L.time + L.dt,
            level=L.level_index,
            iter=step.status.iter,
            sweep=L.status.sweep,
            type="jac_post_step",
            value=jacM,
        )

        P.clear_jac()
