QI_PARALLEL = ["MIN-SR-NS", "MIN-SR-S", "MIN-SR-FLEX"]
QI_SERIAL = ["IE", "EE", "LU", "Picard"]
SDC_METHODS = QI_SERIAL + QI_PARALLEL
RADAU_METHODS = ["RadauIIA5", "RadauIIA7", "RadauIIA9"]
RK_METHODS = ["DOPRI5"]
